#!/bin/sh

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none

# or set your networking parameters here (if a USB network adapter is attached)
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'net' or 'disk'
kernel_loc=disk

# can be either 'net', or 'disk' or 'initrd'
rootfs_loc=disk

# can be any regular filesystem like ext2, ext3, reiserfs in case of 'rootfs_loc=disk'
rootfs_type=ext3

# Where is the rootfs in case of 'rootfs_loc=disk'
rootfs_part=mmcblk0p4

# Where is the rootfs in case of 'rootfs_loc=net'
nfsroot=FIXME

# Where to get the kernel image in case of 'kernel_loc=disk'
kernel_part=disk0.2

# Where to get the device tree image in case of 'kernel_loc=disk'
oftree_loc=env/oftree

# base kernel parameter
bootargs="console=ttyAMA0,115200 rw rootwait"

autoboot_timeout=2

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
