#!/bin/sh

# can be either 'net' or 'nand''
kernel=net
root=net

uimage=uImage-a9m2410
jffs2=root-a9m2410.jffs2

autoboot_timeout=3

nfsroot="/nfsexport/OSELAS.BSP-Hesch-TMU-1/platform-FS_A9M2410/root"
bootargs="console=ttySAC0,38400"

nand_parts="256k(barebox)ro,128k(bareboxenv),1536k(kernel),-(root)"
rootpart_nand="/dev/mtdblock3"

# use 'dhcp' to do dhcp in barebox and in kernel
#ip=dhcp

# or set your networking parameters here
eth0.ipaddr=192.168.42.31
eth0.netmask=255.255.0.0
eth0.gateway=192.168.23.1
eth0.serverip=192.168.23.2
eth0.ethaddr=00:04:f3:00:06:35
