#!/bin/sh

eth0.serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp' or 'nand'
kernel_loc=tftp
# can be either 'net', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-${global.hostname}.${rootfs_type}

kernelimage=zImage-${global.hostname}
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="${user}"-"${kernelimage}"
	nfsroot="${eth0.serverip}:/home/${user}/nfsroot/${global.hostname}"
	rootfsimage="${user}"-"${rootfsimage}"
else
	nfsroot="${eth0.serverip}:/path/to/nfs/root"
fi

autoboot_timeout=3

#
# "mini2440" kernel parameter
# 0 .. 9 = screen type
# b = backlight enabled
# t = touch enabled
# c = camera enabled
# Note: can be "minit2440= " if nothing of these components are connected
#
bootargs="console=ttySAC0,115200 mini2440=0tbc"

# TODO NOR support

nand_device="nand"
nand_parts="256k(barebox),128k(bareboxenv),1536k(kernel),-(root)"
rootfs_mtdblock_nand=3
