obj-$(CONFIG_GPIOLIB)		+= gpio.o
obj-$(CONFIG_GPIO_BCM2835)	+= gpio-bcm2835.o
obj-$(CONFIG_GPIO_CLPS711X)	+= gpio-clps711x.o
obj-$(CONFIG_GPIO_GENERIC)	+= gpio-generic.o
obj-$(CONFIG_GPIO_PL061)	+= gpio-pl061.o
obj-$(CONFIG_GPIO_STMPE)	+= gpio-stmpe.o
