obj-$(CONFIG_GPIOLIB)		+= gpiolib.o

obj-$(CONFIG_GPIO_BCM2835)	+= gpio-bcm2835.o
obj-$(CONFIG_GPIO_CLPS711X)	+= gpio-clps711x.o
obj-$(CONFIG_GPIO_GENERIC)	+= gpio-generic.o
obj-$(CONFIG_GPIO_IMX)		+= gpio-imx.o
obj-$(CONFIG_GPIO_ORION)	+= gpio-orion.o
obj-$(CONFIG_GPIO_PL061)	+= gpio-pl061.o
obj-$(CONFIG_GPIO_STMPE)	+= gpio-stmpe.o
obj-$(CONFIG_GPIO_TEGRA)	+= gpio-tegra.o
obj-$(CONFIG_GPIO_DESIGNWARE)	+= gpio-dw.o
