# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BOARD_ERIZO_GENERIC)	+= erizo/
obj-$(CONFIG_BOARD_HIFIVE)		+= hifive/
obj-$(CONFIG_BOARD_BEAGLEV)		+= beaglev/
obj-$(CONFIG_BOARD_LITEX_LINUX)		+= litex-linux/
obj-$(CONFIG_BOARD_RISCVEMU)		+= riscvemu/
