obj-y				+= common.o
obj-$(CONFIG_ARCH_ARMADA_370)	+= armada-370.o corediv.o
obj-$(CONFIG_ARCH_ARMADA_XP)	+= armada-xp.o corediv.o
obj-$(CONFIG_ARCH_DOVE)		+= dove.o
obj-$(CONFIG_ARCH_KIRKWOOD)	+= kirkwood.o
