#!/bin/sh

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp-barebox
global.dhcp.vendor_id=barebox-at91rm9200ek

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp' or 'nor'
kernel_loc=nfs
# can be either 'net', 'nor' or 'initrd'
rootfs_loc=net
# can be either 'nfs', 'tftp', or empty
oftree_loc=nfs

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root.$rootfs_type

#kernelimage=zImage
kernelimage=uImage
#kernelimage=Image
#kernelimage=Image.lzo

nor_parts="256k(barebox)ro,64k(bareboxenv),3M(kernel),-(root)"
rootfs_mtdblock_nor=3

autoboot_timeout=3

bootargs="console=ttyS0,115200"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;31m[barebox@\h]:\w\e[0m\n# "

