/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) 2018 Christian Hemp
 *
 * Varios wrappers and macros needed to intgrate code generated by
 * i.MX8M DDR Tool into rest of Barebox
 */
#include <common.h>
#include <io.h>
#include <soc/imx8m/ddr.h>

/*
 * Code generated by i.MX8 M DDR Tool doesn't have any prefixes in the
 * global identifiers below, so in order to avoid symbol name
 * collisions with other boards we re-name them via a #define
 */
#define ddr_init	phytec_imx8mq_phycore_ddr_init
#define ddr_cfg_phy	phytec_imx8mq_phycore_ddr_cfg_phy

void phytec_imx8mq_phycore_ddr_init(void);
void phytec_imx8mq_phycore_ddr_cfg_phy(void);
