#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "MMC (ext)"
	exit
fi

global.bootm.image="/mnt/disk0.1/zImage-cfa10036"
global.bootm.oftree="/mnt/disk0.1/oftree-cfa10036"
bootargs-root-ext -r 3 -m mmcblk0p3
