#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "MMC (ext)"
	exit
fi

global.bootm.image="/mnt/disk0.2/zImage-${global.hostname}"
global.bootm.oftree="/mnt/disk0.2/oftree-${global.board.variant}"
global.linux.bootargs.dyn.root="root=/dev/mmcblk0p4 rootfstype=ext3 rootwait"
