# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)		+= phy-core.o
obj-$(CONFIG_USB_NOP_XCEIV)		+= usb-nop-xceiv.o
obj-y					+= freescale/
obj-$(CONFIG_PHY_STM32_USBPHYC) 	+= phy-stm32-usbphyc.o
obj-y					+= rockchip/
obj-$(CONFIG_GENERIC_PHY_MIPI_DPHY)	+= phy-core-mipi-dphy.o
