#!/bin/sh

# board defaults, do not change in running system. Change /env/config
# instead

global.allow_color=true
global.autoboot_timeout=3
global.bootm.oftree="/dev/dtb"
global.linux.bootargs.base="console=ttyAMA0,115200n8 CONSOLE=/dev/ttyAMA0"
global.boot.default=/env/boot.d
