#!/bin/sh

if [ "$1" = menu ]; then
        boot-menu-add-entry "$0" "Kernel:nand;rootfs:nand"
        exit
fi

global.bootm.image="/dev/nand0.kernel.bb"
#global.bootm.oftree="/env/oftree"
bootargs-ip
global.linux.bootargs.dyn.root="root=ubi0:root ubi.mtd=nand0.root rootfstype=ubifs"

