#!/bin/sh

#user=

# Enter MAC address here if not retrieved automatically
#eth0.ethaddr=de:ad:be:ef:00:00

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.serverip=a.b.c.d
#eth0.gateway=a.b.c.d

# can be either 'tftp', 'nfs', 'nand' or 'disk'
kernel_loc=nand
# can be either 'net', 'nand', 'disk' or 'initrd'
rootfs_loc=nand

# for flash based rootfs: 'jffs2' or 'ubifs'
# in case of disk any regular filesystem like 'ext2', 'ext3', 'reiserfs'
rootfs_type=jffs2
# where is the rootfs in case of 'rootfs_loc=disk' (linux name)
rootfs_part_linux_dev=mmcblk0p4
rootfsimage=rootfs-${global.hostname}.$rootfs_type

# where is the kernel image in case of 'kernel_loc=disk'
kernel_part=disk0.2

# The image type of the kernel. Can be uimage, zimage, raw or raw_lzo
#kernelimage=zImage-${global.hostname}
kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

bareboximage=barebox-${global.hostname}.bin
bareboxenvimage=barebox-${global.hostname}.bin

if [ -n $user ]; then
	bareboximage="$user"-"$bareboximage"
	bareboxenvimage="$user"-"$bareboxenvimage"
	kernelimage="$user"-"$kernelimage"
	rootfsimage="$user"-"$rootfsimage"
	nfsroot="/home/$user/nfsroot/${global.hostname}"
else
	nfsroot="/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttyO2,115200"

# the following displays are supported
# pd050vl1 (640 x 480)
# pd035vl1 (640 x 480)
# pd104slf (800 x 600)
# pm070wl4 (800 x 480)
#
# omapfb.mode=<display>:<mode>,[,...]
# omapfb.debug=<y|n>
#        - Enable debug printing. You have to have OMAPFB debug support enabled
#          in kernel config.
#
bootargs="$bootargs omapdss.def_disp=pd050vl1"
#bootargs="$bootargs omapdss.def_disp=pd035vl1"
#bootargs="$bootargs omapdss.def_disp=pd104slf"
#bootargs="$bootargs omapdss.def_disp=pm070wl4"

nand_parts="128k(x-loader)ro,512k(barebox),128k(bareboxenv),4M(kernel),-(root)"
nand_device=omap2-nand.0
rootfs_mtdblock_nand=4

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
