/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _STARFIVE_SYSMAIN_H_
#define _STARFIVE_SYSMAIN_H_

#define SYSMAIN_PLL0_REG			0x00
#define SYSMAIN_PLL1_REG			0x04
#define SYSMAIN_PLL2_REG			0x08
#define SYSMAIN_PLLS_STAT			0x0c

#define SYSMAIN_GMAC_PHY_INTF_SEL		0x70
#define SYSMAIN_GMAC_GTXCLK_DLYCHAIN_SEL	0xC8


#endif //_SYSCON_SYSMAIN_CTRL_MACRO_H_
