obj-y += init.o

obj-$(CONFIG_AT91_BOOTSTRAP) += usb_a9263_bootstrap.o

lwl-$(CONFIG_AT91SAM926X_LWL) += usb_a9263_lowlevel_init.o

bbenv-$(CONFIG_DEFAULT_ENVIRONMENT_GENERIC) += defaultenv-usb-a926x
