
# Generic NAND options
obj-$(CONFIG_NAND)			+= nand_ecc.o
obj-$(CONFIG_NAND_ECC_BCH)		+= nand_bch.o
obj-$(CONFIG_MTD_NAND_IDS)		+= nand_ids.o
obj-$(CONFIG_NAND)			+= nand_base.o nand-bb.o nand_timings.o
obj-$(CONFIG_NAND_BBT)			+= nand_bbt.o

obj-$(CONFIG_MTD_NAND_NOMADIK)		+= nomadik_nand.o
obj-$(CONFIG_NAND_IMX)			+= nand_imx.o
obj-$(CONFIG_NAND_IMX_BBM)		+= nand_imx_bbm.o
obj-$(CONFIG_NAND_OMAP_GPMC)		+= nand_omap_gpmc.o nand_omap_bch_decoder.o
obj-$(CONFIG_NAND_ORION)		+= nand_orion.o
obj-$(CONFIG_NAND_MRVL_NFC)		+= nand_mrvl_nfc.o
obj-$(CONFIG_NAND_ATMEL)		+= atmel_nand.o
obj-$(CONFIG_NAND_S3C24XX)		+= nand_s3c24xx.o
pbl-$(CONFIG_NAND_S3C24XX)		+= nand_s3c24xx.o
obj-$(CONFIG_NAND_MXS)			+= nand_mxs.o
obj-$(CONFIG_MTD_NAND_DENALI)		+= nand_denali.o
obj-$(CONFIG_MTD_NAND_DENALI_DT)	+= nand_denali_dt.o

