# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_MTD_NAND_CORE) += core.o bbt.o nand-bb.o

obj-y += raw/

obj-$(CONFIG_MTD_NAND_ECC) += ecc.o
obj-$(CONFIG_MTD_NAND_ECC_SW_HAMMING) += ecc-sw-hamming.o
obj-$(CONFIG_MTD_NAND_ECC_SW_BCH) += ecc-sw-bch.o
