# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_JTAG)		+= jtag.o
obj-$(CONFIG_SRAM)		+= sram.o
obj-$(CONFIG_STATE_DRV)		+= state.o
obj-$(CONFIG_DEV_MEM)		+= mem.o
obj-$(CONFIG_DEV_PORT)		+= port.o
obj-$(CONFIG_UBOOTVAR)		+= ubootvar.o
obj-$(CONFIG_STARFIVE_PWRSEQ)	+= starfive-pwrseq.o
obj-$(CONFIG_STORAGE_BY_ALIAS)	+= storage-by-alias.o
