#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=net
root=net

uimage=uImage-pcm043
jffs2=root-pcm043.jffs2

autoboot_timeout=3

nfsroot="/path/to/nfs_root"
bootargs="console=ttymxc0,115200"

nor_parts="256k(uboot)ro,128k(ubootenv),2048k(kernel),-(root)"
rootpart_nor="/dev/mtdblock3"

# use 'dhcp' to do dhcp in uboot and in kernel
ip=dhcp

# or set your networking parameters here
eth0.ipaddr=192.168.3.11
eth0.netmask=255.255.255.0
#eth0.gateway=a.b.c.d
#eth0.serverip=192.168.3.10
#eth0.ethaddr=aa.bb.cc.dd.ee.ff

