#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "nand (UBI)"
	exit
fi

global.bootm.image="/dev/nand0.kernel.bb"
#global.bootm.oftree="/env/oftree"
global.linux.bootargs.dyn.root="root=ubi0:rootfs ubi.mtd=nand0.rootfs rootfstype=ubifs"
