# SPDX-License-Identifier: GPL-2.0-only

#
# only unsed by the pbl
#
pbl-y += misc.o
pbl-y += string.o
pbl-$(CONFIG_HAVE_IMAGE_COMPRESSION) += decomp.o
pbl-$(CONFIG_LIBFDT) += fdt.o
pbl-$(CONFIG_PBL_CONSOLE) += console.o
