#!/bin/sh

# can be either 'net' or 'flash'
kernel=net
root=net

# use 'dhcp' todo dhcp in barebox and in kernel
ip=dhcp

#
# setup default ethernet address
#
eth0.ipaddr=192.168.0.99
eth0.netmask=255.255.255.0
eth0.gateway=192.168.0.110
eth0.serverip=192.168.0.110

uimage=uImage-mcf5475
jffs2=root-mcf5475-ptx.jffs2

autoboot_timeout=3

#nfsroot="/home/cschlote/src/bitshrine/ltib/rootfs"
nfsroot="/home/cschlote/src/pengutronics/ptxdist-project-KP-UKD/root-debug,v3"
bootargs="console=ttyS0 rw initcall_debug debug"

#
# setup the partitions in the main flash
#
mtdparts=512k(self),256k(env),3M(kernel),-(root)
rootpart="/dev/mtdblock3"

