#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=net
root=net

uimage=uImage-pcm043
jffs2=root-pcm043.jffs2

autoboot_timeout=3

nfsroot="/ptx/work/octopus/rsc/svn/oselas/bsp/phytec/phyCORE-i.MX27/OSELAS.BSP-Phytec-phyCORE-i.MX27-trunk/root"
bootargs="console=ttymxc0,115200"

nor_parts="256k(barebox)ro,128k(bareboxenv),2048k(kernel),-(root)"
rootpart_nor="/dev/mtdblock3"

nand_parts="256k(barebox)ro,128k(bareboxenv),2048k(kernel),108416k(root),-(kernel1)"
rootpart_nand="/dev/mtdblock7"

# use 'dhcp' to do dhcp in barebox and in kernel
#ip=dhcp

# or set your networking parameters here
eth0.ipaddr=192.168.3.11
eth0.netmask=255.255.255.0
#eth0.gateway=a.b.c.d
eth0.serverip=192.168.3.10
#eth0.ethaddr=
