
obj-$(CONFIG_NAND)	+= nand_base.o
obj-$(CONFIG_NAND)	+= nand_bbt.o
obj-$(CONFIG_NAND)	+= nand.o
obj-$(CONFIG_NAND)	+= nand_ecc.o
obj-$(CONFIG_NAND)	+= nand_ids.o
obj-$(CONFIG_NAND_IMX)	+= nand_imx.o
#obj-$(CONFIG_NAND)	+= nand_util.o
