
# Generic NAND options
obj-$(CONFIG_NAND)			+= nand.o nand_ecc.o
obj-$(CONFIG_MTD_NAND_IDS)		+= nand_ids.o
obj-$(CONFIG_NAND)			+= nand_base.o nand_bbt.o

obj-$(CONFIG_MTD_NAND_DISKONCHIP)	+= diskonchip.o
obj-$(CONFIG_NAND_IMX)			+= nand_imx.o
#obj-$(CONFIG_NAND)			+= nand_util.o
