# drive types

obj-$(CONFIG_DISK_BIOS) += disk_bios_drive.o
obj-$(CONFIG_DISK_IDE_SFF) += ide-sff.o
obj-$(CONFIG_DISK_ATA) += disk_ata_drive.o
obj-$(CONFIG_DISK_AHCI) += ahci.o
obj-$(CONFIG_DISK_AHCI_IMX) += sata-imx.o
obj-$(CONFIG_DISK_SATA_MV) += sata_mv.o

# interface types

obj-$(CONFIG_DISK_INTF_PLATFORM_IDE) += intf_platform_ide.o
obj-$(CONFIG_DISK_PATA_IMX) += pata-imx.o
