# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the rest of the USB drivers
# (the ones that don't fit into any other categories)
#
obj-$(CONFIG_USB_HUB_USB251XB)		+= usb251xb.o
obj-$(CONFIG_USB_ONBOARD_DEV)		+= onboard_usb_dev.o
