#!/bin/sh

mtdparts="512k(nor0.bareboxlow),4M(nor0.kernel),512k(nor0.oftree),26M(nor0.root),512k(nor0.barebox),512k(nor0.bareboxenv)"
kernelname="physmap-flash.0"

mtdparts-add -d nor0 -k ${kernelname} -p ${mtdparts}
