# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_USB_GADGET) += core.o

obj-$(CONFIG_USB_GADGET_DRIVER_ARC) += fsl_udc.o
pbl-$(CONFIG_USB_GADGET_DRIVER_ARC_PBL) += fsl_udc_pbl.o
obj-$(CONFIG_USB_GADGET_DRIVER_AT91) += at91_udc.o
obj-$(CONFIG_USB_GADGET_DRIVER_PXA27X) += pxa27x_udc.o
