# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FS) += file.o
obj-$(CONFIG_DISK) += disk.o
obj-$(CONFIG_VIDEO) += gop.o
obj-$(CONFIG_CONSOLE_FULL) += console.o
obj-$(CONFIG_EFI_LOADER_HII) += hii.o hii_config.o
obj-$(CONFIG_EFI_LOADER_UNICODE_COLLATION_PROTOCOL2) += unicode_collation.o
obj-$(CONFIG_EFI_LOADER_RNG) += rng.o
obj-$(CONFIG_EFI_LOADER_DEVICE_PATH_UTIL) += device_path_utilities.o
obj-$(CONFIG_EFI_LOADER_DEVICE_PATH_TO_TEXT) += device_path_to_text.o
