# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FS) += file.o
obj-$(CONFIG_DISK) += disk.o
obj-$(CONFIG_VIDEO) += gop.o
obj-$(CONFIG_CONSOLE_FULL) += console.o
obj-$(CONFIG_EFI_LOADER_HII) += hii.o hii_config.o
