obj-y += rockchip.o
pbl-$(CONFIG_ARCH_RK3568) += atf.o
obj-$(CONFIG_ARCH_RK3188) += rk3188.o
obj-$(CONFIG_ARCH_RK3288) += rk3288.o
obj-pbl-$(CONFIG_ARCH_RK3568) += rk3568.o
obj-$(CONFIG_ARCH_RK3568) += bootm.o
obj-$(CONFIG_BAREBOX_UPDATE) += bbu.o
