#!/bin/sh

global.bootm.image="/dev/nor0.kernel"
global.linux.bootargs.dyn.root="root=ubi0:root ubi.mtd=5 rootfstype=ubifs"

dtb=/dev/nor0.dtb
filetype -s t ${dtb}
if [ "$t" = dtb ]; then
	global.bootm.oftree="${dtb}"
fi
