# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_NET_9P) := 9pnet.o
obj-$(CONFIG_NET_9P_VIRTIO) += 9pnet_virtio.o

9pnet-objs := \
	mod.o \
	client.o \
	protocol.o

9pnet_virtio-objs := \
	trans_virtio.o \
