// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2007 Juergen Beisert <jbe@pengutronix.de>

obj-y					+= eukrea_cpuimx35.o
lwl-y					+= lowlevel.o
bbenv-$(CONFIG_DEFAULT_ENVIRONMENT_GENERIC) += defaultenv-eukrea_cpuimx35
