obj-$(CONFIG_COMMON_CLK) +=	\
	clk-composite-8m.o	\
	clk-pllv1.o		\
	clk-pllv2.o		\
	clk-pllv3.o		\
	clk-pfd.o		\
	clk-gate2.o		\
	clk-gate-exclusive.o	\
	clk-cpu.o		\
	clk-frac-pll.o		\
	clk-sccg-pll.o		\
	clk.o

obj-$(CONFIG_ARCH_IMX1)   += clk-imx1.o
obj-$(CONFIG_ARCH_IMX25)  += clk-imx25.o
obj-$(CONFIG_ARCH_IMX21)  += clk-imx21.o
obj-$(CONFIG_ARCH_IMX27)  += clk-imx27.o
obj-$(CONFIG_ARCH_IMX31)  += clk-imx31.o
obj-$(CONFIG_ARCH_IMX35)  += clk-imx35.o
obj-$(CONFIG_ARCH_IMX50)  += clk-imx5.o
obj-$(CONFIG_ARCH_IMX51)  += clk-imx5.o
obj-$(CONFIG_ARCH_IMX53)  += clk-imx5.o
obj-$(CONFIG_ARCH_IMX6)   += clk-imx6.o
obj-$(CONFIG_ARCH_IMX6SX) += clk-imx6sx.o
obj-$(CONFIG_ARCH_IMX6SL) += clk-imx6sl.o
obj-$(CONFIG_ARCH_IMX6UL) += clk-imx6ul.o
obj-$(CONFIG_ARCH_IMX7) += clk-imx7.o
obj-$(CONFIG_ARCH_IMX8MQ) += clk-imx8mq.o
obj-$(CONFIG_ARCH_VF610)  += clk-vf610.o
