#!/bin/sh

eth0.ipaddr=192.168.0.50
eth0.netmask=255.255.0.0
eth0.serverip=192.168.0.8
eth0.ethaddr=80:81:82:83:84:85

board=edb9301
autoboot_timeout=3
active_cfg=1
bootargs_common="console=ttyAM0,115200"

# valid media: flash/net
kernel_boot_media=flash
rootfs_boot_media=flash

