obj-$(CONFIG_DRIVER_NET_AT91_ETHER)	+= bcm5221.o
obj-$(CONFIG_DRIVER_NET_AT91_ETHER)	+= dm9161.o
obj-$(CONFIG_DRIVER_NET_AT91_I2C)	+= i2c.o
obj-y			+= interrupts.o
obj-y			+= lowlevel_init.o
obj-$(CONFIG_DRIVER_NET_AT91_ETHER)	+= lxt972.o
obj-y	+= serial.o
# obj-y	+= usb_ohci.o
