obj-y                 += start.o
obj-y                 += exceptions.o
obj-y                 += cpu.o
obj-$(CONFIG_USE_IRQ) += interrupts.o
obj-y                 += traps.o
extra-y               += barebox.lds
