#!/bin/sh

# automount tftp server based on $eth1.serverip

mkdir -p /mnt/tftp
automount /mnt/tftp 'ifup eth1 && mount -t tftp $eth1.serverip /mnt/tftp'

# eth0 is on the mezzanine board
mkdir -p /mnt/tftp-eth0
automount /mnt/tftp-eth0 'ifup eth0 && mount -t tftp $eth0.serverip /mnt/tftp'
