# SPDX-License-Identifier: GPL-2.0-only
obj-y	+= regmap.o
obj-y	+= regmap-mmio.o
obj-$(CONFIG_REGMAP_FORMATTED)	+= regmap-fmt.o
obj-$(CONFIG_I2C)	+= regmap-i2c.o
obj-$(CONFIG_REGMAP_SPI)	+= regmap-spi.o
