# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_EFI_PAYLOAD)	+= payload/
obj-$(CONFIG_EFI_LOADER_BUILD)	+= loader/
obj-$(CONFIG_EFI_RUNTIME)	+= runtime/
obj-$(CONFIG_EFI_GUID)		+= guid.o
obj-$(CONFIG_EFI_DEVICEPATH)	+= devicepath.o
obj-$(CONFIG_EFI)		+= errno.o handle.o efivar.o efivar-filename.o
obj-$(CONFIG_EFI)		+= initrd.o
