# SPDX-License-Identifier: GPL-2.0-only

obj-y += board.o
obj-y += riscvemu-sram.dtbo.o
bbenv-$(CONFIG_CMD_TUTORIAL) += defaultenv-riscvemu

clean-files := *.dtb *.dtb.S .*.dtc .*.pre .*.dts *.dtb.z
clean-files += *.dtbo *.dtbo.S .*.dtso
