# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_BUS_OMAP_GPMC)	+= omap-gpmc.o
obj-$(CONFIG_IMX_WEIM)		+= imx-weim.o
obj-$(CONFIG_MVEBU_MBUS)	+= mvebu-mbus.o
obj-$(CONFIG_TI_SYSC)		+= ti-sysc.o
obj-$(CONFIG_ACPI)		+= acpi.o
obj-$(CONFIG_OF_SIMPLE_PM_BUS)	+= simple-pm-bus.o
