obj-$(CONFIG_COMMON_CLK)	+= clk.o clk-fixed.o clk-divider.o clk-fixed-factor.o \
				clk-mux.o clk-gate.o clk-composite.o \
				clk-fractional-divider.o clk-conf.o \
				clk-gate-shared.o
obj-$(CONFIG_CLKDEV_LOOKUP)	+= clkdev.o

obj-$(CONFIG_ARCH_MVEBU)	+= mvebu/
obj-$(CONFIG_ARCH_MXS)		+= mxs/
obj-$(CONFIG_ARCH_ROCKCHIP)	+= rockchip/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_CLK_SOCFPGA)	+= socfpga.o
obj-$(CONFIG_MACH_MIPS_ATH79)	+= clk-ar933x.o
obj-$(CONFIG_ARCH_IMX)		+= imx/
