# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_COMMON_CLK)	+= clk.o clk-fixed.o clk-divider.o clk-fixed-factor.o \
				clk-mux.o clk-gate.o clk-composite.o \
				clk-fractional-divider.o clk-conf.o \
				clk-gate-shared.o clk-gpio.o \
				clk-bulk.o
obj-$(CONFIG_CLKDEV_LOOKUP)	+= clkdev.o

obj-$(CONFIG_ARCH_MVEBU)	+= mvebu/
obj-$(CONFIG_ARCH_MXS)		+= mxs/
obj-$(CONFIG_ARCH_ROCKCHIP)	+= rockchip/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_ARCH_ZYNQ)		+= zynq/
obj-$(CONFIG_ARCH_ZYNQMP)	+= zynqmp/
obj-$(CONFIG_CLK_SOCFPGA)	+= socfpga/
obj-$(CONFIG_SOC_QCA_AR9331)	+= clk-ar933x.o
obj-$(CONFIG_SOC_QCA_AR9344)	+= clk-ar9344.o
obj-$(CONFIG_ARCH_IMX)		+= imx/
obj-$(CONFIG_COMMON_CLK_AT91)	+= at91/
obj-$(CONFIG_ARCH_STM32MP)	+= clk-stm32mp1.o
obj-$(CONFIG_MACH_VEXPRESS)	+= vexpress/
obj-$(CONFIG_MACH_MIPS_LOONGSON)+= loongson/
obj-$(CONFIG_ARCH_LAYERSCAPE)	+= clk-qoric.o
