# SPDX-License-Identifier: GPL-2.0-only
obj-y	+= bus.o
obj-y	+= driver.o
obj-y	+= platform.o
obj-y	+= resource.o
obj-y	+= class.o
obj-y	+= regmap/

obj-$(CONFIG_PM_GENERIC_DOMAINS) += power.o
obj-$(CONFIG_FEATURE_CONTROLLER) += featctrl.o
obj-$(CONFIG_SOC_BUS) += soc.o
