#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=nor
root=nor
rootfstype=ubifs

basedir=cpuimx27
uimage=$basedir/uImage
rootfs=$basedir/rootfs

autoboot_timeout=1

# DVI-SVGA DVI-VGA CMO-QVGA
video="CMO-QVGA"
bootargs="console=ttymxc0,115200 fec_mac=$eth0.ethaddr video=mxcfb:$video"

nor_parts="256k(barebox)ro,128k(bareboxenv),2432k(kernel),-(root)"
rootpart_nor="/dev/mtdblock3"

nand_parts="-(nand)"
rootpart_nand=""

rootpartnum=3
ubiroot="eukrea-cpuimx27-rootfs"

nfsroot=""

# use 'dhcp' to do dhcp in barebox and in kernel
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d
