#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "MMC (ext3)"
	exit
fi

global.bootm.image="/boot/zImage"
#global.bootm.oftree="/boot/oftree"
global.linux.bootargs.dyn.root="root=mmcblk0p2 rootfstype=ext3 rootwait"
