#!/bin/sh

machine=armadillo2
serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=tftp
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=disk

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-$machine.$rootfs_type

# The image type of the kernel. Can be uimage, zimage, raw, or raw_lzo
kernelimage=zImage-$machine

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$serverip:/home/$user/nfsroot/$machine"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttymxc2,115200"

disk_parts="1M(barebox)ro,3M(bareboxenv),4M(kernel),-(root)"

rootfs_part_linux_dev=sda1
rootfs_type=ext2

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
