#!/bin/sh

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp' or 'nand'
kernel_loc=tftp
# can be either 'net', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root.$rootfs_type

#kernelimage=zImage
kernelimage=uImage
#kernelimage=Image
#kernelimage=Image.lzo

# Partition			Size	Start
# XloaderTOC + X-Loader		256KB	0x00000000
# Memory init function		256KB	0x00040000
# Barebox + env			2MB	0x00080000
# Kernel Image			3MB	0x00280000
# JFFS2 Root filesystem		22MB	0x00580000
# JFFS2 User Data		100MB	0x01b80000

nand_parts="256k(xloader)ro,256k(meminit),2M(barebox),3M(kernel),22M(rootfs),100M(userfs),384k(free),128k(bareboxenv)"

autoboot_timeout=3

bootargs="root=/dev/ram0 console=ttyAMA1,115200n8 init=linuxrc"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "

