#!/bin/sh

global.bootm.image="/dev/m25p0.kernel"

bootargs-ip

# Use rootfs form NAND for now as rootfs partition < 4MB
global.linux.bootargs.dyn.root="root=ubi0:root ubi.mtd=nand0.root,2048 rw rootfstype=ubifs"
