# SPDX-License-Identifier: GPL-2.0

obj-y += protocols/
obj-y += memory.o pool_alloc.o
obj-y += trace.o
obj-y += table.o
obj-y += devicepath.o
obj-y += debug_support.o
obj-y += boot.o
obj-y += runtime.o
obj-y += setup.o
obj-y += watchdog.o
obj-y += pe.o
