obj-y 				+= cpu.o
obj-y				+= cpu_init.o
obj-y				+= loadtask.o
obj-y				+= speed.o
obj-y				+= traps.o
obj-y				+= time.o
extra-y				+= start.o
obj-$(CONFIG_MPC5200)		+= firmware_sc_task_bestcomm.impl.o
obj-$(CONFIG_REGINFO)		+= reginfo.o

#obj-y				+= firmware_sc_task.impl.o
#obj-y				+= io.o
#obj-y				+= ide.o
#obj-y				+= pci_mpc5200.o
