#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NOR partitions"
	exit
fi

mtdparts="256k(barebox),256k(bareboxenv),3584k(kernel),-(root)"
kernelname="physmap-flash.0"

mtdparts-add -d nor0 -k ${kernelname} -p ${mtdparts}
