#!/bin/sh

#user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.serverip=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.ethaddr=de:ad:be:ef:00:00

# can be either 'tftp', 'nfs', 'nand', 'nor' or 'disk'
kernel_loc=tftp
# can be either 'net', 'nand', 'nor', 'disk' or 'initrd'
rootfs_loc=net

# for flash based rootfs: 'jffs2' or 'ubifs'
# in case of disk any regular filesystem like 'ext2', 'ext3', 'reiserfs'
rootfs_type=ext2
# where is the rootfs in case of 'rootfs_loc=disk' (linux name)
rootfs_part_linux_dev=mmcblk0p4
rootfsimage=rootfs-${global.hostname}.$rootfs_type

# where is the kernel image in case of 'kernel_loc=disk'
kernel_part=disk0.2

kernelimage=zImage-${global.hostname}
bareboximage=barebox-${global.hostname}.bin
bareboxenvimage=barebox-${global.hostname}.bin

if [ -n $user ]; then
	bareboximage="$user"-"$bareboximage"
	bareboxenvimage="$user"-"$bareboxenvimage"
	kernelimage="$user"-"$kernelimage"
	rootfsimage="$user"-"$rootfsimage"
	nfsroot="/home/$user/nfsroot/${global.hostname}"
else
	nfsroot="/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttyAMA0,115200"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
