#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=nor
root=nor

uimage=uImage-mmccpu
jffs2=root-mmccpu.jffs2

autoboot_timeout=3

nfsroot="/home/kschwinne/src/pengutronix/OSELAS.BSP-Bucyrus-Grabowski-trunk/platform-Bucyrus-mmccpu/root"

bootargs="console=ttyS0,115200 mmccpu=p299"

#nor_parts="256k(uboot)ro,128k(ubootenv),1536k(kernel),-(root)"
nor_parts="256k(uboot)ro,128k(ubootenv),1536k(kernel),10240k(root),10240k(rootbu),-(data)"
rootpart_nor="/dev/mtdblock3"

#nand_parts="256k(uboot)ro,64k(ubootenv),1536k(kernel),-(root)"
#rootpart_nand="/dev/mtdblock7"

# use 'dhcp' to do dhcp in uboot and in kernel
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d
