#
# Makefile for RTC class/drivers.
#

obj-$(CONFIG_RTC_LIB)           += rtc-lib.o
obj-$(CONFIG_RTC_CLASS)         += class.o

# Keep the list ordered.

obj-$(CONFIG_RTC_DRV_ABRACON)   += rtc-abracon.o
obj-$(CONFIG_RTC_DRV_DS1307)    += rtc-ds1307.o
obj-$(CONFIG_RTC_DRV_JZ4740)	+= rtc-jz4740.o
