# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for RTC class/drivers.
#

obj-$(CONFIG_RTC_LIB)           += rtc-lib.o
obj-$(CONFIG_RTC_CLASS)         += class.o
obj-$(CONFIG_RTC_NVMEM)         += nvmem.o

# Keep the list ordered.

obj-$(CONFIG_RTC_DRV_ABRACON)   += rtc-abracon.o
obj-$(CONFIG_RTC_DRV_DS1307)    += rtc-ds1307.o
obj-$(CONFIG_RTC_DRV_IMXDI)	+= rtc-imxdi.o
obj-$(CONFIG_RTC_DRV_JZ4740)	+= rtc-jz4740.o
obj-$(CONFIG_RTC_DRV_PCF85063)	+= rtc-pcf85063.o
obj-$(CONFIG_RTC_DRV_PCF85363)	+= rtc-pcf85363.o
