# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_USB)		+= core/
obj-$(CONFIG_USB_IMX_CHIPIDEA)	+= imx/
obj-$(CONFIG_USB_DWC2)		+= dwc2/
obj-$(CONFIG_USB_DWC3)		+= dwc3/
obj-$(CONFIG_USB_MUSB)		+= musb/
obj-$(CONFIG_USB_STORAGE)	+= storage/
obj-y += host/
obj-y += otg/
obj-y += gadget/
obj-y += typec/
obj-$(CONFIG_USB)		+= misc/

