obj-y += board.o
obj-y += flash-header-fs700-m60-6s.dcd.o flash-header-fs700-m60-6q.dcd.o
extra-y += flash-header-fs700-m60-6s.dcd.S flash-header-fs700-m60-6q.dcd.S
extra-y += flash-header-fs700-m60-6s.dcd flash-header-fs700-m60-6q.dcd
lwl-y += lowlevel.o
