# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_BOARD_8DEVICES_LIMA) += 8devices-lima/
obj-$(CONFIG_BOARD_BLACK_SWIFT) += black-swift/
obj-$(CONFIG_BOARD_CI20) += img-ci20/
obj-$(CONFIG_BOARD_DLINK_DIR320) += dlink-dir-320/
obj-$(CONFIG_BOARD_DPTECHNICS_DPT_MODULE) += dptechnics-dpt-module/
obj-$(CONFIG_BOARD_OPENEMBEDED_SOM9331) += openembed-som9331/
obj-$(CONFIG_BOARD_OKUD_MAX9331) += okud-max9331/
obj-$(CONFIG_BOARD_LOONGSON_TECH_LS1B) += loongson-ls1b/
obj-$(CONFIG_BOARD_NETGEAR_WG102) += netgear-wg102/
obj-$(CONFIG_BOARD_QEMU_MALTA) += qemu-malta/
obj-$(CONFIG_BOARD_RZX50) += ritmix-rzx50/
obj-$(CONFIG_BOARD_TPLINK_MR3020) += tplink-mr3020/
obj-$(CONFIG_BOARD_TPLINK_WDR4300) += tplink-wdr4300/

pbl-$(CONFIG_BOARD_MIPS_GENERIC_DT) += board-dt-2nd.o
