#!/bin/sh

mtdparts="128k(nand0.xload),256k(nand0.barebox)ro,128k(nand0.bareboxenv),128k(nand0.oftree),4M(nand0.kernel),120M(nand0.rootfs),-(nand0.data)"
kernelname="omap2-nand"

mtdparts-add -b -d nand0 -k ${kernelname} -p ${mtdparts}
