# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_NET_USB)			+= usbnet.o
obj-$(CONFIG_NET_USB_ASIX)		+= asix.o
obj-$(CONFIG_USB_NET_AX88179_178A)	+= ax88179_178a.o
obj-$(CONFIG_NET_USB_SMSC95XX)		+= smsc95xx.o
obj-$(CONFIG_NET_USB_RTL8152)		+= r8152.o r8152_fw.o
