pbl-y += cyclone5-init.o cyclone5-freeze-controller.o cyclone5-scan-manager.o cyclone5-system-manager.o
pbl-y += cyclone5-clock-manager.o
obj-y += cyclone5-generic.o nic301.o cyclone5-bootsource.o cyclone5-reset-manager.o
obj-$(CONFIG_ARCH_SOCFPGA_XLOAD) += xload.o
