#!/bin/sh

hostname=scb9328
eth0.serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'net', 'nor' or 'nand'
kernel_loc=net
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-$hostname.$rootfs_type

kernelimage=zImage-$hostname
#kernelimage=uImage-$hostname
#kernelimage=Image-$hostname
#kernelimage=Image-$hostname.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/$hostname"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttymxc0,115200"

nor_parts="256k(barebox)ro,128k(bareboxenv),2M(kernel),-(root)"
rootfs_mtdblock_nor=3

nand_parts="256k(barebox)ro,128k(bareboxenv),2M(kernel),-(root)"
rootfs_mtdblock_nand=7

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "

