# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_ARCH_IMX)		+= imx/
obj-$(CONFIG_KVX)		+= kvx/
obj-$(CONFIG_ARCH_ROCKCHIP)	+= rockchip/
obj-$(CONFIG_CPU_SIFIVE)	+= sifive/
obj-$(CONFIG_SOC_STARFIVE)	+= starfive/
obj-y += ti/
