#!/bin/sh

# can be either 'net' or 'flash'
kernel=net
root=net

# use 'dhcp' todo dhcp in uboot and in kernel
#ip=dhcp

eth0.ipaddr=192.168.23.164
eth0.netmask=255.255.255.0
eth0.gateway=192.168.23.2
eth0.serverip=192.168.23.2
eth0.ethaddr=00:50:c2:72:a7:4a

uimage=uImage-bfin
jffs2=root-bfin.jffs2
appimage=apps-bfin
perimage=pers-bfin
envimage=uEnv-bfin

autoboot_timeout=1

nfsroot="/ptx/work/octopus/wsa/svn/OSELAS.BSP-Pipetronix-ipe337-trunk/root"
bootargs="console=ttyBF0,115200"

mtdparts="128k(uboot)ro,128k(ubootenv),128k(ageing),1280k(kernel0),1280k(kernel1),8704k(system0),8704k(system1),8320k(application),4096k(persistent)"
ageing=/dev/nor0.ageing
