#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "AHCI (UEFI boot partiton)"
	exit
fi

path="/mnt/ahci-boot"

global.bootm.image="${path}/zImage"

. /env/data/oftree

oftree=${path}/oftree
if [ -f $oftree ]; then
	global.bootm.oftree="$oftree"
fi

# The rootdevice may actually be mmcblk1p2 if a card
# is inserted to the back MMC slot
global.linux.bootargs.dyn.root="root=/dev/sda2"
