# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_FS_CRAMFS)	+= cramfs/
obj-$(CONFIG_FS_EXT4)	+= ext4/
obj-$(CONFIG_FS_RAMFS)	+= ramfs.o
obj-y			+= devfs-core.o
obj-$(CONFIG_FS_LEGACY) += legacy.o
obj-$(CONFIG_FS_DEVFS)	+= devfs.o
obj-pbl-$(CONFIG_FS_FAT)	+= fat/
obj-y	+= fs.o libfs.o
obj-$(CONFIG_NETFS_SUPPORT)	+= netfs.o
obj-$(CONFIG_FS_JFFS2)	+= jffs2/
obj-$(CONFIG_FS_UBIFS)	+= ubifs/
obj-$(CONFIG_FS_TFTP)	+= tftp.o
obj-$(CONFIG_FS_OMAP4_USBBOOT)	+= omap4_usbbootfs.o
obj-$(CONFIG_FS_NFS)	+= nfs.o
obj-$(CONFIG_9P_FS)	+= 9p/
obj-$(CONFIG_FS_BPKFS) += bpkfs.o
obj-$(CONFIG_FS_UIMAGEFS)	+= uimagefs.o
obj-$(CONFIG_FS_EFI)	 += efi.o
obj-$(CONFIG_FS_EFIVARFS) += efivarfs.o
obj-$(CONFIG_FS_SMHFS) += smhfs.o
obj-$(CONFIG_FS_PSTORE) += pstore/
obj-$(CONFIG_FS_SQUASHFS) += squashfs/
obj-$(CONFIG_FS_RATP)	+= ratpfs.o
obj-$(CONFIG_FS_UBOOTVARFS) += ubootvarfs.o
