obj-y += board.o
lwl-y += lowlevel.o
extra-y += flash-header-imx6ul-pico-hobbit-256.dcd.S \
           flash-header-imx6ul-pico-hobbit-256.dcd \
           flash-header-imx6ul-pico-hobbit-512.dcd.S \
           flash-header-imx6ul-pico-hobbit-512.dcd
bbenv-y += defaultenv-pico-hobbit
