#!/bin/sh

global.hostname=clps711x

# set to false if you do not want to have colors
global.allow_color=true

# user (used for network filenames)
global.user=anonymous

# timeout in seconds before the default boot entry is started
global.autoboot_timeout=2

# default boot entry (one of /env/boot/*)
if [ -e /dev/nor0 ]; then
	global.boot.default=nor
fi

# default bootargs
global.linux.bootargs.base="earlyprintk console=ttyCL0,57600n8"
