// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2007 Juergen Beisert <jbe@pengutronix.de>

lwl-y += lowlevel_init.o
obj-y += 3stack.o
bbenv-$(CONFIG_DEFAULT_ENVIRONMENT_GENERIC) += defaultenv-freescale-mx25-3ds
