obj-$(CONFIG_BMP)	+= bmp.o
obj-$(CONFIG_IMAGE_RENDERER)	+= image_renderer.o graphic_utils.o
obj-$(CONFIG_PNG)	+= png.o
obj-$(CONFIG_LODEPNG)	+= png_lode.o lodepng.o
obj-$(CONFIG_PICOPNG)	+= png_pico.o picopng.o
