obj-$(CONFIG_BZLIB)	+= bzlib.o bzlib_crctable.o bzlib_decompress.o bzlib_huffman.o bzlib_randtable.o
obj-$(CONFIG_ZLIB)	+= zlib.o
obj-y			+= crc32.o
obj-y			+= ctype.o
obj-y			+= display_options.o
obj-y			+= ldiv.o
obj-y			+= string.o
obj-y			+= vsprintf.o
obj-y			+= div64.o
obj-y			+= misc.o
obj-y			+= driver.o
obj-y			+= parameter.o
obj-y			+= global.o

