#!/bin/sh

path=/mnt/usb
global.bootm.image=${path}/zImage
initrd=${path}/initrd

if [ -f ${initrd} ]; then
	global.bootm.initrd=${initrd}
	global.linux.bootargs.base="console=ttyO0,115200n8 root=/dev/ram0"
else
	global.linux.bootargs.base="console=ttyO0,115200n8"
fi
