#!/bin/sh

# ip setting (static/dhcp)
ip=dhcp
global.dhcp.vendor_id=barebox-${global.hostname}

# static setup used if ip=static
ipaddr=
netmask=
gateway=
serverip=

# MAC address if needed
#ethaddr=xx:xx:xx:xx:xx:xx

# put code to discover eth1 (i.e. 'usb') to /env/network/eth1-discover

exit 0
