# SPDX-License-Identifier: GPL-2.0-only
#
# fixdep: used to generate dependency information during build process
# sconfigpost: used to postprocess security configs

hostprogs-always-y	+= fixdep
hostprogs-always-y	+= sconfigpost
