CFLAGS_pbl-entry.o := \
	-mcpu=arm7tdmi -march=armv4t \
	-fno-tree-switch-conversion -fno-jump-tables
soc := tegra20
lwl-y += entry.o
extra-y += colibri-t20_256_hsmmc.bct colibri-t20_256_v11_nand.bct \
           colibri-t20_256_v12_nand.bct colibri-t20_512_hsmmc.bct \
           colibri-t20_512_v11_nand.bct colibri-t20_512_v12_nand.bct