# SPDX-License-Identifier: GPL-2.0-only

CFLAGS_entry.pbl.o := -mcpu=arm7tdmi -march=armv4t
soc := tegra20
lwl-y += entry.o
obj-y += board.o
extra-y += colibri-t20_256_hsmmc.bct colibri-t20_256_v11_nand.bct \
           colibri-t20_256_v12_nand.bct colibri-t20_512_hsmmc.bct \
           colibri-t20_512_v11_nand.bct colibri-t20_512_v12_nand.bct
