# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_NET_DSA_REALTEK_MDIO) 	+= realtek-mdio.o tagger.o
obj-$(CONFIG_NET_DSA_REALTEK_SMI) 	+= realtek-smi.o tagger.o
obj-$(CONFIG_NET_DSA_REALTEK_RTL8366RB) += rtl8366rb.o
obj-$(CONFIG_NET_DSA_REALTEK_RTL8365MB) += rtl8365mb.o
obj-$(CONFIG_NET_DSA_TAG_RTL4_A)	+= tag_rtl4_a.o
obj-$(CONFIG_NET_DSA_TAG_RTL8_4)	+= tag_rtl8_4.o
