#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "general config settings"
	exit
fi

# timeout in seconds before the default boot entry is started
global.autoboot_timeout=3

# default boot entry (one of /env/boot/*)
global.boot.default=mmc-ext3
