#!/bin/sh

machine=ccmx51

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp' or 'nand'
kernel_loc=nand
# can be either 'net', 'nand' or 'initrd'
rootfs_loc=nand

# rootfs
rootfs_type=cramfs

# kernel
kernelimage_type=zimage
kernel_img=/dev/nand0.kernel

autoboot_timeout=3

bootargs="console=ttymxc0,115200"

device_type="nand"
nand_device="mxc_nand"
nand_parts="512k(barebox)ro,256k(bareboxenv),3328k(kernel),-(root)"
rootfs_mtdblock_nand=3

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
