#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NOR partitions"
	exit
fi

mtdparts="128k(m25p0.xload),512k(m25p0.barebox),128k(m25p0.bareboxenv),4M(m25p0.kernel),-(m25p0.root)"
kernelname="spi_flash"

mtdparts-add -d m25p0 -k ${kernelname} -p ${mtdparts}

