#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NOR partitions"
	exit
fi

mtdparts="128k(nor0.xload),512k(nor0.barebox),128k(nor0.bareboxenv),4M(nor0.kernel),-(nor0.root)"
kernelname="spi_flash"

mtdparts-add -d nor0 -k ${kernelname} -p ${mtdparts}

