#!/bin/sh

if [ ${global.allow_color} != "true" ]; then
	exit
fi

# Colors
export RED='\e[1;31m'
export BLUE='\e[1;34m'
export GREEN='\e[1;32m'
export CYAN='\e[1;36m'
export YELLOW='\e[1;33m'
export PINK='\e[1;35m'
export WHITE='\e[1;37m'

export DARK_RED='\e[2;31m'
export DARK_BLUE='\e[2;34m'
export DARK_GREEN='\e[2;32m'
export DARK_CYAN='\e[2;36m'
export DARK_YELLOW='\e[2;33m'
export DARK_PINK='\e[2;35m'
export DARK_WHITE='\e[2;37m'

export RED_INV='\e[1;41m'
export BLUE_INV='\e[1;44m'
export GREEN_INV='\e[1;42m'
export CYAN_INV='\e[1;46m'
export ORANGE_INV='\e[1;43m'
export PINK_INV='\e[1;45m'
export NC='\e[0m' # No Color
