# SPDX-License-Identifier: GPL-2.0-or-later
#
# barebox image generation Makefile for Xilinx Zynq UltraScale+
#

pblb-$(CONFIG_MACH_XILINX_ZCU104) += start_zynqmp_zcu104
FILE_barebox-zynqmp-zcu104.img = start_zynqmp_zcu104.pblb
image-$(CONFIG_MACH_XILINX_ZCU104) += barebox-zynqmp-zcu104.img
