#
# barebox image generation Makefile for Xilinx Zynq images
#
quiet_cmd_zynq_image = ZYNQIMG  $@
      cmd_zynq_image = $(objtree)/scripts/zynq_mkimage $(subst .zynqimg,,$@) $@
$(obj)/%.zynqimg: $(obj)/% FORCE
	$(call if_changed,zynq_image)

#------------------------------------------------------------------------------

FILE_barebox-avnet-zedboard.img = start_pbl.pblb.zynqimg
image-$(CONFIG_MACH_ZEDBOARD) += barebox-avnet-zedboard.img
