# SPDX-License-Identifier: GPL-2.0-only

quiet_cmd_bswap32_image = BSWAP4  $@
      cmd_bswap32_image = cp $< $@ && \
			  truncate -s %4 $@ && \
			  objcopy -I binary --reverse-byte=4 $@

$(obj)/%.img.swapped: $(obj)/%.img FORCE
	$(call if_changed,bswap32_image)

pblb-$(CONFIG_BOARD_QEMU_MALTA) += start_qemu_malta
FILE_barebox-qemu-malta.img = start_qemu_malta.pblb
image-$(CONFIG_BOARD_QEMU_MALTA) += barebox-qemu-malta.img barebox-qemu-malta.img.swapped
