#
# barebox image generation Makefile for VExpress images
#

pblb-$(CONFIG_MACH_VEXPRESS) += start_vexpress_ca9
FILE_barebox-vexpress-ca9.img = start_vexpress_ca9.pblb
image-$(CONFIG_MACH_VEXPRESS) += barebox-vexpress-ca9.img

pblb-$(CONFIG_MACH_VEXPRESS) += start_vexpress_ca15
FILE_barebox-vexpress-ca15.img = start_vexpress_ca15.pblb
image-$(CONFIG_MACH_VEXPRESS) += barebox-vexpress-ca15.img
