# SPDX-License-Identifier: GPL-2.0-or-later

SYMLINK_TARGET_barebox = sandbox_main.elf
symlink-$(CONFIG_SANDBOX) += barebox

ifeq ($(CONFIG_SANDBOX),y)

quiet_cmd_elf__ = LD      $@
      cmd_elf__ = $(CC) -o $@ $(BAREBOX_LDFLAGS) \
	-Wl,-T,$(pbl-lds) -Wl,--defsym=main=$(2) -Wl,--whole-archive \
	$(obj)/../$(BAREBOX_PROPER) $(BAREBOX_PBL_OBJS) -Wl,--no-whole-archive \
	-lrt -pthread $(SANDBOX_LIBS) $(LDFLAGS_$(@F))

endif
