#!/bin/sh

mtdparts="0xC0000(nand0.bootstrap),256k(nand0.barebox)ro,128k(nand0.bareboxenv),3M(nand0.kernel),-(nand0.rootfs)"
kernelname="atmel_nand"

mtdparts-add -b -d nand0 -k ${kernelname} -p ${mtdparts}
