obj-y += compr.o dir.o nodelist.o malloc.o
obj-y += read.o readinode.o scan.o
obj-y += build.o fs.o
obj-y += super.o debug.o

obj-$(CONFIG_FS_JFFS2_COMPRESSION_ZLIB) += compr_zlib.o
obj-$(CONFIG_FS_JFFS2_COMPRESSION_LZO) += compr_lzo.o
obj-$(CONFIG_FS_JFFS2_COMPRESSION_RTIME) += compr_rtime.o
obj-$(CONFIG_FS_JFFS2_COMPRESSION_RUBIN) += compr_rubin.o
