# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_ARCH_SOCFPGA_CYCLONE5)	+= clk.o
obj-$(CONFIG_ARCH_SOCFPGA_ARRIA10)	+= clk.o

obj-$(CONFIG_ARCH_SOCFPGA_ARRIA10) += clk-gate-a10.o clk-periph-a10.o clk-pll-a10.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX5) += clk-agilex5.o clk-pll-s10.o clk-periph-s10.o clk-gate-s10.o
