# SPDX-License-Identifier: GPL-2.0-only

obj-y                 += start.o
obj-y                 += cpu.o
obj-y                 += exceptions.o
obj-y                 += cache.o
extra-y               += barebox.lds
