# SPDX-License-Identifier: GPL-2.0-only
obj-y += clk.o
obj-y += clk-pll.o
obj-y += clk-cpu.o
obj-y += clk-inverter.o
obj-y += clk-mmc-phase.o
obj-y += clk-muxgrf.o
obj-y += gate-link.o

obj-$(CONFIG_RESET_CONTROLLER) += softrst.o
obj-$(CONFIG_ARCH_RK3188) += clk-rk3188.o
obj-$(CONFIG_ARCH_RK3288) += clk-rk3288.o
obj-$(CONFIG_ARCH_RK3568) += clk-rk3568.o
obj-$(CONFIG_ARCH_RK3576) += clk-rk3576.o rst-rk3576.o
obj-$(CONFIG_ARCH_RK3588) += clk-rk3588.o rst-rk3588.o
