#!/bin/sh

eth0.serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=tftp
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-${global.hostname}.$rootfs_type

kernelimage=zImage-${global.hostname}
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/${global.hostname}"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttyO2,115200"

nand_parts="128k(xload)ro,512k(barebox),128k(bareboxenv),4M(kernel),4M(splash),-(root)"
nand_device="omap2-nand.0"
rootfs_mtdblock_nand=5

#Displays
# Splashscreen-Display can be either '', 'pd050vl1', 'pm070wl4', 'pd104slf', 'g104x1'
# 'edt_etm0350G0dh6', 'edt_etm0430G0dh6', 'edt_etmv570G2dhu' or 'edt_etm0700G0dh6'
# to use dvi output in kernel set 'display=dvi' and
# dvi_resolution to '640x480-60' '800x600-60' or '1024x768-60'

display=edt_etm0700G0dh6
#dvi_resolution=1024x768-60

if [ -n ${global.displayargs} ]; then
	bootargs="$bootargs ${global.displayargs}"
fi

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "

