#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=net
root=net

uimage=uImage-PM9263
jffs2=root-PM9263.jffs2

autoboot_timeout=3

nfsroot="/ptx/work/octopus/mkl/bucyrus/OSELAS.BSP-Bucyrus-Grabowski-trunk/platform-Ronetix-PM9263/root"
bootargs="console=ttyS0,115200"

nor_parts="256k(barebox)ro,64k(bareboxenv),1536k(kernel),-(root)"
rootpart_nor="/dev/mtdblock3"

#nand_parts="256k(barebox)ro,64k(bareboxenv),1536k(kernel),-(root)"
#rootpart_nand="/dev/mtdblock7"

# use 'dhcp' to do dhcp in barebox and in kernel
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
eth0.serverip=192.168.23.1
