obj-pbl-y			+= common.o
obj-$(CONFIG_ARCH_ARMADA_370)	+= armada-370-xp.o
obj-$(CONFIG_ARCH_ARMADA_XP)	+= armada-370-xp.o
obj-$(CONFIG_ARCH_ARMADA_38X)	+= armada-370-xp.o
obj-$(CONFIG_ARCH_DOVE)		+= dove.o
obj-$(CONFIG_ARCH_KIRKWOOD)	+= kirkwood.o
obj-$(CONFIG_BAREBOX_UPDATE)	+= kwb_bbu.o
obj-$(CONFIG_BOOTM)		+= kwbootimage.o
