CFLAGS_tegra_avp_init.o := \
	-mcpu=arm7tdmi -march=armv4t \
	-fno-tree-switch-conversion -fno-jump-tables
CFLAGS_pbl-tegra_avp_init.o := \
	-mcpu=arm7tdmi -march=armv4t \
	-fno-tree-switch-conversion -fno-jump-tables
CFLAGS_tegra_maincomplex_init.o := \
	-fno-tree-switch-conversion -fno-jump-tables
CFLAGS_pbl-tegra_maincomplex_init.o := \
	-fno-tree-switch-conversion -fno-jump-tables
lwl-y += tegra_avp_init.o
lwl-y += tegra_maincomplex_init.o
obj-y += tegra20.o
obj-y += tegra20-pmc.o
obj-y += tegra20-timer.o
