#!/bin/sh

if [ -f /mnt/sd/zImage ]; then
	global.boot.default=sd-card-linux
elif [ -f /mnt/sd/android ]; then
	global.boot.default=sd-card-android
elif [ -f /mnt/usb/zImage ]; then
	global.boot.default=usb-linux
elif [ -f /mnt/usb/android ]; then
	global.boot.default=usb-android
fi
