#!/bin/sh

# change network settings in /env/network/eth0
# change mtd partition settings and automountpoints in /env/init/*

#global.hostname=

# set to false if you do not want to have colors
global.allow_color=true

# user (used for network filenames)
global.user=none

# timeout in seconds before the default boot entry is started
global.autoboot_timeout=3

# default boot entry (one of /env/boot/*)
global.boot.default=net

# base bootargs
#global.linux.bootargs.base="console=ttyS0,115200"
