obj-y                      += board.o
obj-y                      += libgcc.o
obj-y                      += clock.o
obj-y                      += cache.o
obj-$(CONFIG_CMD_BOOTM)    += bootm.o
obj-$(CONFIG_EARLY_PRINTF) += early_printf.o

