#!/bin/sh

# otg port mode : can be 'host' or 'device'
otg_mode="device"
# video : can be CMO-QVGA, URT-WVGA, DVI-VGA or DVI-SVGA
video="CMO-QVGA"

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp' or 'nand'
kernel_loc=nand
# can be either 'net', 'nand' or 'initrd'
rootfs_loc=nand

# rootfs
rootfs_type=ubifs
rootfsimage=${global.hostname}/rootfs.$rootfs_type

# kernel
kernelimage=${global.hostname}/uImage-${global.hostname}.bin

# barebox and it's env
bareboximage=${global.hostname}/barebox-${global.hostname}.bin
bareboxenvimage=${global.hostname}/bareboxenv-${global.hostname}.bin

nfsroot="$eth0.serverip:/srv/nfs/${global.hostname}"

autoboot_timeout=1

bootargs="console=ttymxc0,115200 otg_mode=$otg_mode video=imxfb:$video"

nand_parts="256k(barebox)ro,128k(bareboxenv),3M(kernel),-(root)"
rootfs_mtdblock_nand=3
nand_device="mxc_nand"
ubiroot="${global.hostname}-rootfs"
device_type="nand"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
