#!/bin/sh

detect mmc1

path="/mnt/mmc1.0"

global.bootm.image="${path}/zImage"
global.bootm.oftree="${path}/vf610-zii-${global.hostname}.dtb"

initramfs="${path}/initramfs"
if [ -f "${initramfs}" ]; then
	global.bootm.initrd="$initramfs"
fi
