# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_BOARD_QEMU_VIRT)	+= qemu-virt/
obj-$(CONFIG_BOARD_PHYTEC_SOM_DETECTION) += phytec/
obj-$(CONFIG_BOARD_TQ) += tq/
obj-$(CONFIG_BOARD_WOLFVISION) += wolfvision/
obj-$(CONFIG_BOARD_LXA) += lxa/
