# SPDX-License-Identifier: GPL-2.0
#
# Copyright 2008-2014 Freescale Semiconductor, Inc.

pbl-y += main.o util.o ctrl_regs.o options.o lc_common_dimm_params.o

pbl-y += ddr1_dimm_params.o
pbl-y += ddr2_dimm_params.o
pbl-y += ddr3_dimm_params.o
pbl-y += ddr4_dimm_params.o
obj-y += arm_ddr_gen3.o
pbl-y += fsl_ddr_gen4.o
