#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	global.boot.default="mmc nand spi net"
elif [ $bootsource = nand ]; then
	global.boot.default="nand spi mmc net"
elif [ $bootsource = spi ]; then
	global.boot.default="spi nand mmc net"
elif [ $bootsource = net ]; then
	global.boot.default="net nand spi mmc"
fi
