# SPDX-License-Identifier: GPL-2.0-only

obj-y 				+= cpu.o
obj-y				+= cpu_init.o
obj-y				+= loadtask.o
obj-y				+= speed.o
obj-y				+= traps.o
obj-y				+= time.o
extra-y				+= start.o
obj-$(CONFIG_MPC5200)		+= firmware_sc_task_bestcomm.impl.o
obj-$(CONFIG_COMMAND_SUPPORT)	+= reginfo.o
