#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NAND partitions"
	exit
fi

mtdparts="256k(nand0.barebox),128k(nand0.bareboxenv),1536k(nand0.kernel),-(nand0.root)"
kernelname="nand"

mtdparts-add -b -d nand0 -k ${kernelname} -p ${mtdparts}
