# atmel_usart.o
# ns9750_serial.o
# s3c4510b_uart.o
# serial_max3100.o
# serial_pl010.o
# serial_pl011.o
# serial_xuartlite.o
obj-$(CONFIG_DRIVER_SERIAL_IMX)			+= serial_imx.o
obj-$(CONFIG_DRIVER_SERIAL_NETX)		+= serial_netx.o
obj-$(CONFIG_DRIVER_SERIAL_LINUX_COMSOLE)	+= linux_console.o
obj-$(CONFIG_DRIVER_SERIAL_MPC5XXX)		+= serial_mpc5xxx.o
obj-$(CONFIG_DRIVER_SERIAL_BLACKFIN)		+= serial_blackfin.o
obj-$(CONFIG_DRIVER_SERIAL_NS16550)		+= serial_ns16550.o
