# atmel_usart.o
# ns9750_serial.o
# s3c4510b_uart.o
# serial_max3100.o
# serial_pl010.o
# serial_xuartlite.o
obj-$(CONFIG_DRIVER_SERIAL_ARM_DCC)		+= arm_dcc.o
obj-$(CONFIG_SERIAL_AMBA_PL011)			+= amba-pl011.o
obj-$(CONFIG_DRIVER_SERIAL_IMX)			+= serial_imx.o
obj-$(CONFIG_DRIVER_SERIAL_STM378X)		+= stm-serial.o
obj-$(CONFIG_DRIVER_SERIAL_ATMEL)		+= atmel.o
obj-$(CONFIG_DRIVER_SERIAL_NETX)		+= serial_netx.o
obj-$(CONFIG_DRIVER_SERIAL_LINUX_COMSOLE)	+= linux_console.o
obj-$(CONFIG_DRIVER_SERIAL_MPC5XXX)		+= serial_mpc5xxx.o
obj-$(CONFIG_DRIVER_SERIAL_BLACKFIN)		+= serial_blackfin.o
obj-$(CONFIG_DRIVER_SERIAL_NS16550)		+= serial_ns16550.o
obj-$(CONFIG_DRIVER_SERIAL_PL010)		+= serial_pl010.o
obj-$(CONFIG_DRIVER_SERIAL_S3C24X0)		+= serial_s3c24x0.o
obj-$(CONFIG_DRIVER_SERIAL_ALTERA)		+= serial_altera.o
