#!/usr/bin/env bash

# Generate the default environment file from a list of directories
# usage: genenv <target> <dir>...
# and <target> is the resulting binary environment
target=$1
shift 1

abspath() {
	local fn dn
	if [ $# -ne 1 ]; then
		echo "usage: ptxd_abspath <path>"
		exit 1
	fi
	if [ -d "${1}" ]; then
		fn=""
		dn="${1}"
	else
		fn="/$(basename "${1}")"
		dn="$(dirname "${1}")"
	fi

	[ ! -d "${dn}" ] && exit 1
	echo "$(cd "${dn}" && pwd)${fn}"
}
export -f abspath

tempdir=$(abspath "${target}.genenv.tmp")
tmpfile="$(mktemp)"

mkdir -p "$tempdir"

for i in $*; do
	if [ -n "${srctree}" ] && [ ! -e "$i" ] && [ -e "$srctree/$i" ]; then
		i="$srctree/$i"
	fi

	if [ -d $i ]; then
		cp -r $i/* $tempdir
	else
		cp -a $i $tempdir
	fi
done

find $tempdir -name '.svn' -o -name '*~' -delete

scripts/bareboxenv -s $tempdir ${tmpfile}

diff "${tmpfile}" "${target}" >/dev/null 2>/dev/null
if [ $? != 0 ]; then
	mv "${tmpfile}" "${target}"
else
	rm ${tmpfile}
fi

rm -r $tempdir
