# SPDX-License-Identifier: GPL-2.0-only

bbenv-suffix-$(CONFIG_DEFAULT_COMPRESSION_GZIP)	:= .gz
bbenv-suffix-$(CONFIG_DEFAULT_COMPRESSED_BZIP2)	:= .bz2
bbenv-suffix-$(CONFIG_DEFAULT_COMPRESSION_LZO)	:= .lzo
bbenv-suffix-$(CONFIG_DEFAULT_COMPRESSION_LZ4)	:= .lz4
bbenv-suffix-$(CONFIG_DEFAULT_COMPRESSION_NONE)	:=

obj-y += $(patsubst %,%.bbenv$(bbenv-suffix-y).o,$(bbenv-y))
extra-y += $(patsubst %,%.bbenv$(bbenv-suffix-y),$(bbenv-y))
extra-y += $(patsubst %,%.bbenv$(bbenv-suffix-y).S,$(bbenv-y))
extra-y += $(patsubst %,%.bbenv$(bbenv-suffix-y).o,$(bbenv-y))

quiet_cmd_env_S = ENV.S   $@
cmd_env_S =							\
(								\
	echo '\#include <asm/barebox.lds.h>';			\
	echo '.section .note.GNU-stack,"",%progbits';		\
	echo '.section .bbenv.rodata.$(subst -,_,$(*F)),"a"';	\
	echo '.balign STRUCT_ALIGNMENT';			\
	echo '.global __bbenv_$(subst -,_,$(*F))_start';	\
	echo '__bbenv_$(subst -,_,$(*F))_start:';		\
	echo '.incbin "$<" ';					\
	echo '__bbenv_$(subst -,_,$(*F))_end:';			\
	echo '.global __bbenv_$(subst -,_,$(*F))_end';		\
	echo '.balign STRUCT_ALIGNMENT';			\
) > $@

$(obj)/%.bbenv$(bbenv-suffix-y).S: $(obj)/%.bbenv$(bbenv-suffix-y) FORCE
	$(call if_changed,env_S)

quiet_cmd_envgen = ENVGEN  $@
cmd_envgen = $(srctree)/scripts/genenv $@ $2

quiet_cmd_env = ENV     $@
cmd_env = $(srctree)/scripts/genenv $@ $<

# genenv is always called, but only generates output when the file actually
# changes, so that the dependent targets are not unnecessarily rebuilt
$(obj)/%.bbenv$(bbenv-suffix-y): $(src)/% FORCE
	$(call cmd,env)
	$(Q)printf '%s\n' 'savedcmd_$@ := $(cmd_env)' > $(dot-target).cmd
