# SPDX-License-Identifier: GPL-2.0-only

# If CONFIG_OF_ALL_DTBS is enabled, all DT blobs are built
dtb-$(CONFIG_OF_ALL_DTBS) += $(dtb-)

dtb-y           := $(addprefix $(obj)/, $(dtb-y))

always-y        += $(dtb-y)

# dtbs-list
# ---------------------------------------------------------------------------

subdir-dtbslist := $(addsuffix /dtbs-list, $(subdir-ym))
dtb-y           += $(subdir-dtbslist)
always-y        += $(obj)/dtbs-list

$(subdir-dtbslist): $(obj)/%/dtbs-list: $(obj)/% ;

$(obj)/dtbs-list: $(dtb-y) FORCE
	$(call if_changed,gen_order)

# DTC
# ---------------------------------------------------------------------------

DTC ?= $(objtree)/scripts/dtc/dtc
FDTGET ?= $(objtree)/scripts/dtc/fdtget
FDTOVERLAY ?= $(objtree)/scripts/dtc/fdtoverlay
DTC_FLAGS += -Wno-unique_unit_address

DTC_FLAGS += -Wno-unit_address_vs_reg \
             -Wno-unit_address_format \
             -Wno-avoid_unnecessary_addr_size \
             -Wno-alias_paths \
             -Wno-graph_child_address \
             -Wno-simple_bus_reg \
             -Wno-pci_device_reg \
             -Wno-interrupt_provider

# Disable noisy checks by default
ifeq ($(findstring 1,$(KBUILD_EXTRA_WARN)),)
DTC_FLAGS += -Wno-interrupt_map
else
DTC_FLAGS += -Wunique_unit_address_if_enabled
endif

ifneq ($(findstring 2,$(KBUILD_EXTRA_WARN)),)
DTC_FLAGS += -Wnode_name_chars_strict \
             -Wproperty_name_chars_strict \
             -Wunique_unit_address
endif

DTC_FLAGS += $(DTC_FLAGS_$(target-stem))

# Set -@ if the target is a base DTB that overlay is applied onto
DTC_FLAGS += $(if $(filter $(patsubst $(obj)/%,%,$@), $(base-dtb-y)), -@)

ifeq ($(CONFIG_OF_OVERLAY_LIVE), y)
DTC_FLAGS.dtb += -@
endif

DTC_FLAGS.dtbo += -Wno-avoid_default_addr_size -Wno-reg_format -Wno-graph_port

# Overlay base device tree
# ---------------------------------------------------------------------------

# DTBO_BASE_<overlay> names the device tree an overlay is written against: it
# is compiled with -@, its label paths written to <base>-paths.h for the
# overlay to target by path, and the overlay applied to it at build time.
dtbo-base = $(DTBO_BASE_$(basename $(1)))
dtbo-bases := $(sort $(foreach o, $(overlay-y), $(call dtbo-base,$(o))))

always-y += $(addprefix $(obj)/, $(addsuffix .dtb, $(dtbo-bases)))
base-dtb-y += $(addsuffix .dtb, $(dtbo-bases))
targets += $(addprefix $(obj)/, $(addsuffix -paths.h, $(dtbo-bases)))

$(foreach o, $(overlay-y), $(if $(call dtbo-base,$(o)), $(eval \
	$(obj)/$(o): $(obj)/$(call dtbo-base,$(o))-paths.h \
		     $(obj)/$(call dtbo-base,$(o)).dtb $(FDTOVERLAY))))

# DT Build Rules
# ---------------------------------------------------------------------------

# Generate an assembly file to wrap the output of the device tree compiler
quiet_cmd_dt_S_dtb = DTB     $@
cmd_dt_S_dtb = $(srctree)/scripts/gen-dtb-s $(subst -,_,$(*F)) $< $(CONFIG_IMD) > $@
$(obj)/%.dtb.S: $(obj)/%.dtb $(obj)/%.dtb.z $(srctree)/scripts/gen-dtb-s FORCE
	$(call if_changed,dt_S_dtb)

# Overlays in overlay-y are registered for the live tree, the rest only linked in
quiet_cmd_dt_S_dtbo = DTBO    $@
cmd_dt_S_dtbo = $(srctree)/scripts/gen-dtbo-s $(subst -,_,$(*F)) $< \
	$(if $(filter $(patsubst $(obj)/%,%,$*).dtbo, $(overlay-y)),y) > $@
$(obj)/%.dtbo.S: $(obj)/%.dtbo $(srctree)/scripts/gen-dtbo-s FORCE
	$(call if_changed,dt_S_dtbo)

$(obj)/%.dtb.z: $(obj)/%.dtb FORCE
	$(call if_changed,$(suffix_y))

# Device tree name
# ---------------------------------------------------------------------------
#
# Stamp every device tree with the name barebox knows it by: the blob's path
# relative to $(obj), but without the arch directory under dts/src, so that the
# name is the one Linux uses too. Overlays are known by the tree they end up in.
#
#   arch/arm/dts/imx6q-foo.dts        -> imx6q-foo.dtb
#   dts/src/arm/nxp/imx/imx6q-foo.dts -> nxp/imx/imx6q-foo.dtb
dtbname-strip-arch = $(subst $(space),/,$(wordlist 2,$(words $(1)),$(1)))
dtbname-path = $(patsubst $(obj)/%,%,$@)
dtbname.dtb = $(if $(filter dts/src,$(obj)),\
		$(call dtbname-strip-arch,$(subst /, ,$(dtbname-path))),$(dtbname-path))

# indirection: the comma in the property name would split the $(if) arguments
dtbname-stamp = / { barebox,dtbname = "$(dtbname$(suffix $@))"; };
cmd_dtbname = $(if $(dtbname$(suffix $@)), \
	echo '$(dtbname-stamp)' >> $(dtc-tmp) ;)

dts-frags = $(CONFIG_EXTERNAL_DTS_FRAGMENTS)
quiet_cmd_dtc = DTC     $@
cmd_dtc = $(CPP) $(dtc_cpp_flags) -x assembler-with-cpp -o $(dtc-tmp) \
	-D'$(subst -,_,$(*F))_dts=1' $(foreach f,$< $(2),-include '$(f)') /dev/null ; \
	$(cmd_dtbname) \
	$(objtree)/scripts/dtc/dtc -O dtb -o $@ -b 0 \
		-i $(srctree)/arch/$(SRCARCH)/dts $(DTC_FLAGS) $(DTC_FLAGS$(suffix $@)) \
		-i $(srctree)/dts/src/$(SRCARCH) \
		-i $(srctree)/dts/src/arm/ti/omap \
		-d $(depfile).dtc $(dtc-tmp) ; \
	cat $(depfile).pre $(depfile).dtc > $(depfile)

$(obj)/%.dtb: $(src)/%.dts FORCE
	$(call if_changed_dep,dtc,$(dts-frags))

quiet_cmd_dtco = DTCO    $@
cmd_dtco = $(cmd_dtc) $(if $(DTBO_BASE_$(target-stem)), ; \
	$(srctree)/scripts/check-dt-overlay $(FDTOVERLAY) $(FDTGET) \
		$(obj)/$(DTBO_BASE_$(target-stem)).dtb $@)

$(obj)/%.dtbo: $(src)/%.dtso $(DTC) FORCE
	$(call if_changed_dep,dtco)

quiet_cmd_dt_paths = DTPATH  $@
cmd_dt_paths = $(srctree)/scripts/gen-dt-paths $(FDTGET) $< > $@ || \
	{ rm -f $@; false; }

$(obj)/%-paths.h: $(obj)/%.dtb $(FDTGET) $(srctree)/scripts/gen-dt-paths FORCE
	$(call if_changed,dt_paths)

dtc-tmp = $(subst $(comma),_,$(dot-target).dts)

# targets
# ---------------------------------------------------------------------------

targets += $(always-y)

# %.dtb.o <- %.dtb.S <- %.dtb <- %.dts
# %.dtbo.o <- %.dtbo.S <- %.dtbo <- %.dtso
targets += $(call intermediate_targets, .dtb.o, .dtb.S .dtb) \
           $(call intermediate_targets, .dtbo.o, .dtbo.S .dtbo)
