obj-y	+= bzlib.o
obj-y	+= bzlib_crctable.o
obj-y	+= bzlib_decompress.o
obj-y	+= bzlib_huffman.o
obj-y	+= bzlib_randtable.o
obj-y	+= crc32.o
obj-y	+= ctype.o
obj-y	+= display_options.o
obj-y	+= ldiv.o
obj-y	+= string.o
obj-y	+= vsprintf.o
obj-y	+= zlib.o
obj-y	+= div64.o

