#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "android (nand)"
	exit
fi

global.bootm.image="/dev/nand0.kernel.bb"
global.linux.bootargs.dyn.root="root=/dev/mtdblock1 rootfstype=jffs2 rw init=/init rootdelay=1"
# clean the mtdparts otherwise android does not boot
global -r linux.mtdparts.
