#!/bin/sh

if [ "$1" = menu ]; then
        boot-menu-add-entry "$0" "SPI NOR Flash"
        exit
fi

global.bootm.image="/dev/m25p0.kernel"

# Use rootfs form SD-Card for now as rootfs partition < 4MB
global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootfstype=ext3 rootwait"

