obj-$(CONFIG_USB_EHCI)		+= ehci-hcd.o
obj-$(CONFIG_USB_EHCI_OMAP)	+= ehci-omap.o
obj-$(CONFIG_USB_EHCI_ATMEL)	+= ehci-atmel.o
obj-$(CONFIG_USB_OHCI)		+= ohci-hcd.o
obj-$(CONFIG_USB_OHCI_PLATFORM)	+= ohci-platform.o
obj-$(CONFIG_USB_XHCI)		+= xhci-hcd.o xhci-hub.o
obj-$(CONFIG_USB_XHCI_PCI)	+= xhci-pci.o
