obj-$(CONFIG_USB_EHCI)		+= ehci-hcd.o
obj-$(CONFIG_USB_EHCI_OMAP)	+= ehci-omap.o
obj-$(CONFIG_USB_EHCI_ATMEL)	+= ehci-atmel.o
obj-$(CONFIG_USB_OHCI)		+= ohci-hcd.o
obj-$(CONFIG_USB_OHCI_AT91)	+= ohci-at91.o
obj-$(CONFIG_USB_DWC2_HOST)	+= dwc2.o
obj-$(CONFIG_USB_XHCI)		+= xhci.o xhci-mem.o xhci-ring.o
