obj-$(CONFIG_USB_EHCI)		+= ehci-hcd.o
obj-$(CONFIG_USB_EHCI_OMAP)	+= ehci-omap.o
obj-$(CONFIG_USB_EHCI_ATMEL)	+= ehci-atmel.o
obj-$(CONFIG_USB_OHCI)		+= ohci-hcd.o
obj-$(CONFIG_USB_OHCI_AT91)	+= ohci-at91.o
