#!/bin/sh

# automount tftp server

mkdir -p /mnt/tftp
automount /mnt/tftp 'ifup -a1 && mount -t tftp $global.net.server /mnt/tftp'

# automount nfs server's nfsroot

mkdir -p /mnt/nfs
automount /mnt/nfs 'ifup -a1 && mount -t nfs ${global.net.server}:/home/${global.user}/nfsroot/${global.hostname} /mnt/nfs'


# FAT on usb disk example

#mkdir -p /mnt/fat
#automount -d /mnt/fat 'usb && [ -e /dev/disk0.0 ] && mount /dev/disk0.0 /mnt/fat'
