obj-y += stacktrace.o
obj-$(CONFIG_ARM_LINUX)	+= armlinux.o
obj-y	+= div0.o
obj-$(CONFIG_ARM_OPTIMZED_STRING_FUNCTIONS)	+= memcpy.o
obj-$(CONFIG_ARM_OPTIMZED_STRING_FUNCTIONS)	+= memset.o string.o
extra-y += barebox.lds
obj-pbl-y   += runtime-offset.o

pbl-y	+= div0.o
