#
# Generic code for Coldfire V4E targets (MCF547x/MCF548x)
#
obj-y += mcf_clocksource.o
obj-y += mcf_reset_cpu.o

#
# FEC support
#
obj-y += multichannel_dma.o
obj-y += dma_utils.o
obj-y += fec.o
obj-y += fecbd.o

#
# FreeScale MultiDMA Library
#
obj-y += mcdapi/
obj-y += net/
