obj-y += phy.o mdio_bus.o
obj-$(CONFIG_AR8327N_PHY)	+= ar8327.o
obj-$(CONFIG_AT803X_PHY)	+= at803x.o
obj-$(CONFIG_DAVICOM_PHY)	+= davicom.o
obj-$(CONFIG_LXT_PHY)		+= lxt.o
obj-$(CONFIG_MARVELL_PHY)	+= marvell.o
obj-$(CONFIG_MICREL_PHY)	+= micrel.o
obj-$(CONFIG_NATIONAL_PHY)	+= national.o
obj-$(CONFIG_SMSC_PHY)		+= smsc.o

obj-$(CONFIG_MDIO_MVEBU)	+= mdio-mvebu.o
obj-$(CONFIG_MDIO_BITBANG)	+= mdio-bitbang.o
obj-$(CONFIG_MDIO_GPIO)		+= mdio-gpio.o
obj-$(CONFIG_MDIO_BUS_MUX)	+= mdio-mux.o
obj-$(CONFIG_MDIO_BUS_MUX_GPIO)	+= mdio-mux-gpio.o

