obj-y += init.o

obj-$(CONFIG_AT91_BOOTSTRAP) += tny_a9263_bootstrap.o


lwl-$(CONFIG_MACH_TNY_A9260) += tny_a9260_lowlevel.o
lwl-$(CONFIG_MACH_TNY_A9G20) += tny_a9260_lowlevel.o
lwl-$(CONFIG_MACH_TNY_A9263) += tny_a9263_lowlevel.o

bbenv-$(CONFIG_DEFAULT_ENVIRONMENT_GENERIC) += defaultenv-tny-a926x
