#!/bin/sh

path="/mnt/internal-hd0.0"

global.bootm.image="${path}/linuximage"

oftree=${path}/oftree
if [ -f $oftree ]; then
	global.bootm.oftree="$oftree"
fi

global.linux.bootargs.dyn.root="root=/dev/sda2"
