obj-$(CONFIG_NAND)			+= nand/
obj-$(CONFIG_DRIVER_CFI)		+= nor/
obj-$(CONFIG_MTD_UBI)			+= ubi/
obj-y					+= devices/
obj-$(CONFIG_PARTITION_NEED_MTD)	+= partition.o
obj-$(CONFIG_MTD)			+= core.o
obj-$(CONFIG_MTD_OOB_DEVICE)		+= mtdoob.o
obj-$(CONFIG_MTD_RAW_DEVICE)		+= mtdraw.o
