#!/bin/sh

hostname=FIXME
if [ -z "$user" ]; then
#	user=
fi

# Enter MAC address here if not retrieved automatically
#eth0.ethaddr=de:ad:be:ef:00:00

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp
global.dhcp.vendor_id=barebox

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.serverip=a.b.c.d
#eth0.gateway=a.b.c.d

# can be either 'tftp', 'nfs', 'nand', 'nor' or 'disk'
kernel_loc=tftp
# can be either 'net', 'nand', 'nor', 'disk' or 'initrd'
rootfs_loc=net
# can be either 'tftp', 'nfs', 'nand', 'nor', 'disk' or none
oftree_loc=tftp

# for flash based rootfs: 'jffs2' or 'ubifs'
# in case of disk any regular filesystem like 'ext2', 'ext3', 'reiserfs'
rootfs_type=ubifs
# where is the rootfs in case of 'rootfs_loc=disk' (linux name)
rootfs_part_linux_dev=mmcblk0p4
rootfsimage=rootfs-${global.hostname}.$rootfs_type

# where is the kernel image in case of 'kernel_loc=disk'
kernel_part=disk0.2

kernelimage=zImage-${global.hostname}
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

bareboximage=barebox-${global.hostname}.bin
bareboxenvimage=barebox-${global.hostname}.bin

if [ -n $user ]; then
	bareboximage="$user"-"$bareboximage"
	bareboxenvimage="$user"-"$bareboxenvimage"
	kernelimage="$user"-"$kernelimage"
	rootfsimage="$user"-"$rootfsimage"
	nfsroot="/home/$user/nfsroot/${global.hostname}"
else
	nfsroot="/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttyFIXME,115200"

nor_parts="256k(barebox)ro,128k(bareboxenv),3M(kernel),-(root)"
rootfs_mtdblock_nor=3

nand_parts="256k(barebox)ro,128k(bareboxenv),3M(kernel),-(root)"
nand_device="FIXME"
rootfs_mtdblock_nand=7

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
