# SPDX-License-Identifier: GPL-2.0-only

obj-y += io-ports.o
obj-y += board.o
obj-y += clock.o
obj-y += hostfile.o
obj-y += console.o
obj-y += devices.o
obj-y += dtb.o
obj-y += power.o
obj-y += dev-random.o
obj-y += watchdog.o
obj-$(CONFIG_LED) += led.o

extra-y += barebox.lds

obj-y += stickypage.o
