# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PWM)		+= core.o
obj-$(CONFIG_PWM_PXA)		+= pxa_pwm.o
obj-$(CONFIG_PWM_ATMEL)		+= pwm-atmel.o
obj-$(CONFIG_PWM_IMX)		+= pwm-imx.o
obj-$(CONFIG_PWM_MXS)		+= pwm-mxs.o
obj-$(CONFIG_PWM_STM32)		+= pwm-stm32.o
obj-$(CONFIG_PWM_ROCKCHIP)	+= pwm-rockchip.o
