#!/bin/sh
# Boot the Amazon factory-shipped kernel uimage stored on
# the eMMC at CONFIG_MMC_BOOTFLASH_ADDR 0x41000

# Force ATAG boot
global.bootm.boot_atag=true

global linux.bootargs.dyn.log="log_pos_goal=0x8fff0000"
global linux.bootargs.dyn.root="rootwait root=/dev/mmcblk0p1 ro"

bootm -c /dev/mmc1.kernel
