#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#
pbl-$(CONFIG_IMX_DRAM) += helper.o ddrphy_utils.o ddrphy_train.o ddrphy_csr.o
pbl-$(CONFIG_IMX8M_DRAM) += imx8m_ddr_init.o
pbl-$(CONFIG_IMX9_DRAM) += imx9_ddr_init.o
