# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multiplexer devices.
#

mux-core-objs			:= core.o
mux-gpio-objs			:= gpio.o

obj-$(CONFIG_MULTIPLEXER)	+= mux-core.o
obj-$(CONFIG_MUX_GPIO)		+= mux-gpio.o
