#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "MMC"
	exit
fi

global.bootm.image="/mnt/mmc/zImage"
global.bootm.oftree="/mnt/mmc/oftree"
global.linux.bootargs.dyn.root="root=mmcblk0p2 rootfstype=ext3 rootwait"
