# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HAVE_OPTEE) += of_fixup.o
obj-$(CONFIG_OPTEE) += optee.o
optee-objs += core.o
optee-objs += call.o
optee-objs += rpc.o
optee-objs += device.o
optee-objs += smc_abi.o
