obj-$(CONFIG_CRC32)	+= crc32.o
obj-$(CONFIG_CRC16)	+= crc16.o
obj-$(CONFIG_CRC7)	+= crc7.o
obj-$(CONFIG_MD5)	+= md5.o
obj-$(CONFIG_SHA1)	+= sha1.o
obj-$(CONFIG_SHA224)	+= sha2.o
obj-$(CONFIG_SHA256)	+= sha2.o
