# Generic NAND options

obj-$(CONFIG_MTD_RAW_NAND)		+= nand_ecc.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_ids.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_base.o  nand_timings.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_legacy.o nand_onfi.o nand_amd.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_esmt.o nand_hynix.o nand_macronix.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_micron.o nand_samsung.o nand_toshiba.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_jedec.o
obj-$(CONFIG_MTD_RAW_NAND)		+= nand_bbt.o

obj-$(CONFIG_MTD_NAND_NOMADIK)		+= nomadik_nand.o
obj-$(CONFIG_NAND_IMX)			+= nand_imx.o
obj-$(CONFIG_NAND_OMAP_GPMC)		+= nand_omap_gpmc.o nand_omap_bch_decoder.o
obj-$(CONFIG_MTD_NAND_OMAP_ELM)		+= omap_elm.o
obj-$(CONFIG_NAND_ORION)		+= nand_orion.o
obj-$(CONFIG_NAND_STM32)		+= stm32_fmc2_nand.o
obj-$(CONFIG_NAND_MRVL_NFC)		+= nand_mrvl_nfc.o
obj-$(CONFIG_NAND_ATMEL)		+= atmel/
obj-$(CONFIG_NAND_MXS)			+= nand_mxs.o
obj-$(CONFIG_MTD_NAND_DENALI)		+= nand_denali.o
obj-$(CONFIG_MTD_NAND_DENALI_DT)	+= nand_denali_dt.o
obj-$(CONFIG_NAND_FSL_IFC)		+= nand_fsl_ifc.o
