#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	global.boot.default="mmc nand spi net"
elif [ $boosource = nand ]; then
	global.boot.default="nand spi mmc net"
elif [ $boosource = spi ]; then
	global.boot.default="spi nand mmc net"
elif [ $boosource = net ]; then
	global.boot.default="net nand spi mmc"
fi
