#!/bin/sh

global.hostname=panda
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=tftp
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=net

kernelimage=zImage-${global.hostname}
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/${global.hostname}"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttyO2,115200"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "

