obj-y += board.o
obj-y += flash-header-tqma6q.dcd.o flash-header-tqma6dl.dcd.o
extra-y += flash-header-tqma6q.dcd.S flash-header-tqma6dl.dcd.S
extra-y += flash-header-tqma6q.dcd flash-header-tqma6dl.dcd
lwl-y += lowlevel.o
