# SPDX-License-Identifier: GPL-2.0-only

lwl-$(CONFIG_BUILTIN_DTB) += $(CONFIG_BUILTIN_DTB_NAME).dtb.o

clean-files := *.dtb *.dtb.S .*.dtc .*.pre .*.dts *.dtb.z
clean-files += *.dtbo *.dtbo.S .*.dtso
