#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NOR partitions"
	exit
fi

mtdparts="512k(nor0.barebox)ro,128k(nor0.bareboxenv),4M(nor0.kernel),-(nor0.root)"
kernelname="physmap-flash.0"

mtdparts-add -d nor0 -k ${kernelname} -p ${mtdparts}
