obj-y                 += clock.o
obj-y                 += board.o
obj-y                 += cpuinfo.o
obj-y                 += muldi3.o
obj-y                 += lshrdi3.o
obj-y                 += ashldi3.o
obj-y                 += ashrdi3.o
