name: build all defconfigs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/barebox/barebox/barebox-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev

    strategy:
      matrix:
        arch: [mips, powerpc, riscv, sandbox, x86 ]
        regex: ["*"]
        include:
          - arch: arm
            regex: "[a-b]*"
          - arch: arm
            regex: "[c-m]*"
          - arch: arm
            regex: "[n-q]*"
          - arch: arm
            regex: "[r-z]*"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        export ARCH=${{matrix.arch}}

        export CROSS_COMPILE_arm=/opt/gcc-12.2.0-nolibc/arm-linux-gnueabi/bin/arm-linux-gnueabi-
        export CROSS_COMPILE_arm64=/opt/gcc-12.2.0-nolibc/aarch64-linux/bin/aarch64-linux-
        export CROSS_COMPILE_mips=/opt/gcc-12.2.0-nolibc/mips-linux/bin/mips-linux-
        export CROSS_COMPILE_powerpc=/opt/gcc-12.2.0-nolibc/powerpc-linux/bin/powerpc-linux-
        export CROSS_COMPILE_riscv=/opt/gcc-12.2.0-nolibc/riscv32-linux/bin/riscv32-linux-

        ./test/generate-dummy-fw.sh

        ./MAKEALL -O build-${{matrix.arch}} -k test/kconfig/disable_size_check.kconf \
                -k test/kconfig/disable_target_tools.kconf -e '${{matrix.regex}}'
