obj-$(CONFIG_NET_DHCP)	+= dhcp.o
obj-$(CONFIG_NET)	+= eth.o
obj-$(CONFIG_NET)	+= net.o
obj-$(CONFIG_NET_NFS)	+= nfs.o
obj-$(CONFIG_NET_PING)	+= ping.o
obj-$(CONFIG_NET_RESOLV)+= dns.o
obj-$(CONFIG_NET_NETCONSOLE) += netconsole.o
