obj-y += clocksource.o
obj-y += common.o
obj-y += gpio.o
obj-y += devices.o
obj-y += sleep.o

obj-$(CONFIG_ARCH_PXA2XX) += mfp-pxa2xx.o
obj-$(CONFIG_ARCH_PXA27X) += speed-pxa27x.o
obj-$(CONFIG_RESET_SOURCE) += reset_source.o
